# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.snowflake_marketplace_offer_payment_terms import SnowflakeMarketplaceOfferPaymentTerms

class TestSnowflakeMarketplaceOfferPaymentTerms(unittest.TestCase):
    """SnowflakeMarketplaceOfferPaymentTerms unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnowflakeMarketplaceOfferPaymentTerms:
        """Test SnowflakeMarketplaceOfferPaymentTerms
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnowflakeMarketplaceOfferPaymentTerms`
        """
        model = SnowflakeMarketplaceOfferPaymentTerms()
        if include_optional:
            return SnowflakeMarketplaceOfferPaymentTerms(
                installment_schedule = {"default_installment_amount":6.519180951018382,"overridden_installments":[{"installment_amount":4.652396432933246,"installment_number":8.969578798196912},{"installment_amount":4.652396432933246,"installment_number":8.969578798196912}],"installment_duration":0.10263654006109402},
                payment_type = 'INVOICE'
            )
        else:
            return SnowflakeMarketplaceOfferPaymentTerms(
        )
        """

    def testSnowflakeMarketplaceOfferPaymentTerms(self):
        """Test SnowflakeMarketplaceOfferPaymentTerms"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
