# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.aws_marketplace_catalog_pricing_term_rate_card_constraints import AwsMarketplaceCatalogPricingTermRateCardConstraints

class TestAwsMarketplaceCatalogPricingTermRateCardConstraints(unittest.TestCase):
    """AwsMarketplaceCatalogPricingTermRateCardConstraints unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwsMarketplaceCatalogPricingTermRateCardConstraints:
        """Test AwsMarketplaceCatalogPricingTermRateCardConstraints
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AwsMarketplaceCatalogPricingTermRateCardConstraints`
        """
        model = AwsMarketplaceCatalogPricingTermRateCardConstraints()
        if include_optional:
            return AwsMarketplaceCatalogPricingTermRateCardConstraints(
                multiple_dimension_selection = '',
                quantity_configuration = ''
            )
        else:
            return AwsMarketplaceCatalogPricingTermRateCardConstraints(
        )
        """

    def testAwsMarketplaceCatalogPricingTermRateCardConstraints(self):
        """Test AwsMarketplaceCatalogPricingTermRateCardConstraints"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
