# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.gcp_marketplace_reseller_private_offer_plan_price_model_template_overage import GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage

class TestGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage(unittest.TestCase):
    """GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage:
        """Test GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage`
        """
        model = GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage()
        if include_optional:
            return GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage(
                discount_template = {"discountPercentage":{"minAmount":{"nanos":1,"units":"units"},"defaultAmount":{"nanos":1,"units":"units"},"maxAmount":{"nanos":1,"units":"units"}},"discountEconomics":"discountEconomics","hideDiscountPercentage":true,"discountedPrice":{"nanos":1,"units":"units","currencyCode":"currencyCode"}},
                sku_discount_templates = [
                    None
                    ],
                sku_representation = {"skuList":{"skus":["skus","skus"]},"skus":"skus","skuGroupList":"{}"}
            )
        else:
            return GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage(
        )
        """

    def testGcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage(self):
        """Test GcpMarketplaceResellerPrivateOfferPlanPriceModelTemplateOverage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
