# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.github_com_sugerio_marketplace_service_pkg_orm_notification_message import GithubComSugerioMarketplaceServicePkgOrmNotificationMessage

class TestGithubComSugerioMarketplaceServicePkgOrmNotificationMessage(unittest.TestCase):
    """GithubComSugerioMarketplaceServicePkgOrmNotificationMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GithubComSugerioMarketplaceServicePkgOrmNotificationMessage:
        """Test GithubComSugerioMarketplaceServicePkgOrmNotificationMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GithubComSugerioMarketplaceServicePkgOrmNotificationMessage`
        """
        model = GithubComSugerioMarketplaceServicePkgOrmNotificationMessage()
        if include_optional:
            return GithubComSugerioMarketplaceServicePkgOrmNotificationMessage(
                creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                info = suger_sdk_python.models.notification_message_info.NotificationMessageInfo(
                    action = suger_sdk_python.models.action.action(), 
                    bcc_recipients = [
                        ''
                        ], 
                    cc_recipients = [
                        ''
                        ], 
                    custom_fields = { }, 
                    html_content = '', 
                    standard_fields = { }, 
                    subject = '', 
                    text_content = '', ),
                organization_id = '',
                recipient = '',
                type = 'EMAIL'
            )
        else:
            return GithubComSugerioMarketplaceServicePkgOrmNotificationMessage(
        )
        """

    def testGithubComSugerioMarketplaceServicePkgOrmNotificationMessage(self):
        """Test GithubComSugerioMarketplaceServicePkgOrmNotificationMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
