# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.api.vendor_api import VendorApi


class TestVendorApi(unittest.TestCase):
    """VendorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VendorApi()

    def tearDown(self) -> None:
        pass

    def test_get_vendor_product(self) -> None:
        """Test case for get_vendor_product

        get vendor product
        """
        pass

    def test_list_vendor_products(self) -> None:
        """Test case for list_vendor_products

        list vendor products
        """
        pass


if __name__ == '__main__':
    unittest.main()
