# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.entitlement_term_info import EntitlementTermInfo

class TestEntitlementTermInfo(unittest.TestCase):
    """EntitlementTermInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntitlementTermInfo:
        """Test EntitlementTermInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntitlementTermInfo`
        """
        model = EntitlementTermInfo()
        if include_optional:
            return EntitlementTermInfo(
                dimension_quantity_decimal_parts = {
                    'key' : 1.337
                    },
                is_commit_divided = True,
                parent_entitlement_term_id = '',
                sub_entitlement_term_ids = [
                    ''
                    ],
                type = ''
            )
        else:
            return EntitlementTermInfo(
        )
        """

    def testEntitlementTermInfo(self):
        """Test EntitlementTermInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
