# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.gcp_marketplace_agreement_document import GcpMarketplaceAgreementDocument

class TestGcpMarketplaceAgreementDocument(unittest.TestCase):
    """GcpMarketplaceAgreementDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GcpMarketplaceAgreementDocument:
        """Test GcpMarketplaceAgreementDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GcpMarketplaceAgreementDocument`
        """
        model = GcpMarketplaceAgreementDocument()
        if include_optional:
            return GcpMarketplaceAgreementDocument(
                eula_agreement_document = {"documentBody":"documentBody","documentType":"documentType","unstructuredDocument":{"content":"content"},"name":"name","description":"description","updateTime":"2000-01-23T04:56:07.000+00:00","externalGoogleLink":"{}"}
            )
        else:
            return GcpMarketplaceAgreementDocument(
        )
        """

    def testGcpMarketplaceAgreementDocument(self):
        """Test GcpMarketplaceAgreementDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
