# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.gcp_marketplace_private_offer_price_model_fixed import GcpMarketplacePrivateOfferPriceModelFixed

class TestGcpMarketplacePrivateOfferPriceModelFixed(unittest.TestCase):
    """GcpMarketplacePrivateOfferPriceModelFixed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GcpMarketplacePrivateOfferPriceModelFixed:
        """Test GcpMarketplacePrivateOfferPriceModelFixed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GcpMarketplacePrivateOfferPriceModelFixed`
        """
        model = GcpMarketplacePrivateOfferPriceModelFixed()
        if include_optional:
            return GcpMarketplacePrivateOfferPriceModelFixed(
                discount = suger_sdk_python.models.gcp_marketplace_private_offer_price_model_discount.GcpMarketplacePrivateOfferPriceModelDiscount(
                    discount_percentage = suger_sdk_python.models.discount_percentage.discountPercentage(), 
                    discounted_price = suger_sdk_python.models.discounted_price.discountedPrice(), ),
                period = {"unit":"MONTHLY_PERIOD","count":4}
            )
        else:
            return GcpMarketplacePrivateOfferPriceModelFixed(
        )
        """

    def testGcpMarketplacePrivateOfferPriceModelFixed(self):
        """Test GcpMarketplacePrivateOfferPriceModelFixed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
