# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.aws_marketplace_product_visibility import AwsMarketplaceProductVisibility

class TestAwsMarketplaceProductVisibility(unittest.TestCase):
    """AwsMarketplaceProductVisibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwsMarketplaceProductVisibility(self):
        """Test AwsMarketplaceProductVisibility"""
        # inst = AwsMarketplaceProductVisibility()

if __name__ == '__main__':
    unittest.main()
