# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.aws_ace_integration import \
    AwsAceIntegration  # noqa: E501


class TestAwsAceIntegration(unittest.TestCase):
    """AwsAceIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwsAceIntegration:
        """Test AwsAceIntegration
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AwsAceIntegration`
        """
        model = AwsAceIntegration()  # noqa: E501
        if include_optional:
            return AwsAceIntegration(
                credential = openapi_client.models.aws_integration_credential.AwsIntegrationCredential(
                    access_key_id = '', 
                    iam_user_arn = '', 
                    secret_access_key = '', ),
                enable_assume_iam_role = True,
                iam_role_arn = '',
                partner_id = '',
                paused = True,
                s3_bucket_name = '',
                s3_bucket_region = '',
                secret_key = ''
            )
        else:
            return AwsAceIntegration(
        )
        """

    def testAwsAceIntegration(self):
        """Test AwsAceIntegration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
