# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_api import APIApi  # noqa: E501


class TestAPIApi(unittest.TestCase):
    """APIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_api_client(self) -> None:
        """Test case for create_api_client

        create api client  # noqa: E501
        """
        pass

    def test_get_api_client(self) -> None:
        """Test case for get_api_client

        get api client  # noqa: E501
        """
        pass

    def test_get_api_client_access_token(self) -> None:
        """Test case for get_api_client_access_token

        get api access token  # noqa: E501
        """
        pass

    def test_list_api_clients(self) -> None:
        """Test case for list_api_clients

        list api clients  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
