# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.aws_invoice import AwsInvoice

class TestAwsInvoice(unittest.TestCase):
    """AwsInvoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwsInvoice:
        """Test AwsInvoice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AwsInvoice`
        """
        model = AwsInvoice()
        if include_optional:
            return AwsInvoice(
                account_id = '',
                amount_due = 1.337,
                billing_entity = '',
                billing_month = 56,
                billing_period_end = '',
                billing_period_start = '',
                billing_year = 56,
                charge_type = '',
                currency_code = '',
                due_date = '',
                id = '',
                invoice_type = '',
                issued_date = '',
                line_items = suger_sdk_python.models.aws_invoice_line_items.AwsInvoiceLineItems(
                    details = [
                        suger_sdk_python.models.aws_invoice_line_item_detail.AwsInvoiceLineItemDetail(
                            charges = 1.337, 
                            currency = '', 
                            product_name = '', )
                        ], 
                    linked_account_allocations = [
                        suger_sdk_python.models.aws_invoice_linked_account_allocation.AwsInvoiceLinkedAccountAllocation(
                            account_id = '', 
                            account_name = '', 
                            allocated_total = 1.337, 
                            currency = '', )
                        ], ),
                pdf_downloaded = True,
                settle_date = '',
                status = '',
                sync_timestamp = '',
                system_identifier_arn = '',
                tax_amount = 1.337,
                total_amount = 1.337,
                total_amount_before_tax = 1.337,
                transaction_status = ''
            )
        else:
            return AwsInvoice(
        )
        """

    def testAwsInvoice(self):
        """Test AwsInvoice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
