# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.azure_marketplace_price_and_availability_custom_meter_price_meter_item_price_item import AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem

class TestAzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem(unittest.TestCase):
    """AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem:
        """Test AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem`
        """
        model = AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem()
        if include_optional:
            return AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem(
                price_per_payment_in_usd = 1.337,
                prices = [
                    {"markets":["markets","markets"],"price":1.0246457001441578,"currency":"currency"}
                    ]
            )
        else:
            return AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem(
        )
        """

    def testAzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem(self):
        """Test AzureMarketplacePriceAndAvailabilityCustomMeterPriceMeterItemPriceItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
