# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.gcp_marketplacce_event_type import GcpMarketplacceEventType

class TestGcpMarketplacceEventType(unittest.TestCase):
    """GcpMarketplacceEventType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGcpMarketplacceEventType(self):
        """Test GcpMarketplacceEventType"""
        # inst = GcpMarketplacceEventType()

if __name__ == '__main__':
    unittest.main()
