# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.microsoft_partner_referral_target_type import MicrosoftPartnerReferralTargetType  # noqa: E501

class TestMicrosoftPartnerReferralTargetType(unittest.TestCase):
    """MicrosoftPartnerReferralTargetType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMicrosoftPartnerReferralTargetType(self):
        """Test MicrosoftPartnerReferralTargetType"""
        # inst = MicrosoftPartnerReferralTargetType()

if __name__ == '__main__':
    unittest.main()
