# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.aws_marketplace_cppo_opportunity_rule_type import AwsMarketplaceCppoOpportunityRuleType

class TestAwsMarketplaceCppoOpportunityRuleType(unittest.TestCase):
    """AwsMarketplaceCppoOpportunityRuleType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwsMarketplaceCppoOpportunityRuleType(self):
        """Test AwsMarketplaceCppoOpportunityRuleType"""
        # inst = AwsMarketplaceCppoOpportunityRuleType()

if __name__ == '__main__':
    unittest.main()
