# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.azure_marketplace_metering_batch_usage_event import AzureMarketplaceMeteringBatchUsageEvent

class TestAzureMarketplaceMeteringBatchUsageEvent(unittest.TestCase):
    """AzureMarketplaceMeteringBatchUsageEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AzureMarketplaceMeteringBatchUsageEvent:
        """Test AzureMarketplaceMeteringBatchUsageEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AzureMarketplaceMeteringBatchUsageEvent`
        """
        model = AzureMarketplaceMeteringBatchUsageEvent()
        if include_optional:
            return AzureMarketplaceMeteringBatchUsageEvent(
                request = [
                    suger_sdk_python.models.azure_marketplace_metering_usage_event.AzureMarketplaceMeteringUsageEvent(
                        dimension = '', 
                        effective_start_time = '', 
                        plan_id = '', 
                        quantity = 1.337, 
                        resource_id = '', 
                        resource_uri = '', )
                    ]
            )
        else:
            return AzureMarketplaceMeteringBatchUsageEvent(
        )
        """

    def testAzureMarketplaceMeteringBatchUsageEvent(self):
        """Test AzureMarketplaceMeteringBatchUsageEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
