# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from suger_sdk_python.models.billing_discount_type import BillingDiscountType

class TestBillingDiscountType(unittest.TestCase):
    """BillingDiscountType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingDiscountType(self):
        """Test BillingDiscountType"""
        # inst = BillingDiscountType()

if __name__ == '__main__':
    unittest.main()
