# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


from openapi_client.models.azure_marketplace_private_offer_type import (
    AzureMarketplacePrivateOfferType,
)  # noqa: E501


class TestAzureMarketplacePrivateOfferType(unittest.TestCase):
    """AzureMarketplacePrivateOfferType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAzureMarketplacePrivateOfferType(self):
        """Test AzureMarketplacePrivateOfferType"""
        # inst = AzureMarketplacePrivateOfferType()


if __name__ == "__main__":
    unittest.main()
