# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class AwsMarketplaceCppoPaymentTermsEntitlement(BaseModel):
    """
    AwsMarketplaceCppoPaymentTermsEntitlement
    """
    name: Optional[StrictStr] = Field(None, description="The commit dimension Key")
    quantity: Optional[StrictInt] = Field(None, description="The commit dimension quantity")
    __properties = ["name", "quantity"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AwsMarketplaceCppoPaymentTermsEntitlement:
        """Create an instance of AwsMarketplaceCppoPaymentTermsEntitlement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AwsMarketplaceCppoPaymentTermsEntitlement:
        """Create an instance of AwsMarketplaceCppoPaymentTermsEntitlement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AwsMarketplaceCppoPaymentTermsEntitlement.parse_obj(obj)

        _obj = AwsMarketplaceCppoPaymentTermsEntitlement.parse_obj({
            "name": obj.get("name"),
            "quantity": obj.get("quantity")
        })
        return _obj


