# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, conlist
from openapi_client.models.cosell_opp_referral import CosellOppReferral

class ListCosellOppReferralsResponse(BaseModel):
    """
    ListCosellOppReferralsResponse
    """
    cosell_opp_referrals: Optional[conlist(CosellOppReferral)] = Field(None, alias="cosellOppReferrals")
    next_offset: Optional[StrictInt] = Field(None, alias="nextOffset", description="If it is nil, it means there is no more records.")
    total_count: Optional[StrictInt] = Field(None, alias="totalCount", description="Only available when the request is made with offset=0.")
    __properties = ["cosellOppReferrals", "nextOffset", "totalCount"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ListCosellOppReferralsResponse:
        """Create an instance of ListCosellOppReferralsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in cosell_opp_referrals (list)
        _items = []
        if self.cosell_opp_referrals:
            for _item in self.cosell_opp_referrals:
                if _item:
                    _items.append(_item.to_dict())
            _dict['cosellOppReferrals'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ListCosellOppReferralsResponse:
        """Create an instance of ListCosellOppReferralsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ListCosellOppReferralsResponse.parse_obj(obj)

        _obj = ListCosellOppReferralsResponse.parse_obj({
            "cosell_opp_referrals": [CosellOppReferral.from_dict(_item) for _item in obj.get("cosellOppReferrals")] if obj.get("cosellOppReferrals") is not None else None,
            "next_offset": obj.get("nextOffset"),
            "total_count": obj.get("totalCount")
        })
        return _obj


