# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MetronomeBillingMode(str, Enum):
    """
    MetronomeBillingMode
    """

    """
    allowed enum values
    """
    QUANTITY = 'quantity'
    AMOUNT_HOURLY = 'amount_hourly'
    AMOUNT_DAILY = 'amount_daily'

    @classmethod
    def from_json(cls, json_str: str) -> MetronomeBillingMode:
        """Create an instance of MetronomeBillingMode from a JSON string"""
        return MetronomeBillingMode(json.loads(json_str))


