# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg


class SalesforceSyncFilterOperator(str, Enum):
    """
    SalesforceSyncFilterOperator
    """

    """
    allowed enum values
    """
    EQ = "EQ"
    NE = "NE"
    GT = "GT"
    GTE = "GTE"
    LT = "LT"
    LTE = "LTE"
    IN = "IN"
    NOTIN = "NOTIN"

    @classmethod
    def from_json(cls, json_str: str) -> SalesforceSyncFilterOperator:
        """Create an instance of SalesforceSyncFilterOperator from a JSON string"""
        return SalesforceSyncFilterOperator(json.loads(json_str))
