# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr


class SalesforceCrmCredential(BaseModel):
    """
    SalesforceCrmCredential
    """

    access_token: Optional[StrictStr] = None
    client_id: Optional[StrictStr] = Field(
        None, description="NOTE(shiman) Debugging purpose only"
    )
    client_secret: Optional[StrictStr] = None
    exp: Optional[StrictInt] = None
    instance_url: Optional[StrictStr] = None
    refresh_token: Optional[StrictStr] = None
    __properties = [
        "access_token",
        "client_id",
        "client_secret",
        "exp",
        "instance_url",
        "refresh_token",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SalesforceCrmCredential:
        """Create an instance of SalesforceCrmCredential from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SalesforceCrmCredential:
        """Create an instance of SalesforceCrmCredential from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SalesforceCrmCredential.parse_obj(obj)

        _obj = SalesforceCrmCredential.parse_obj(
            {
                "access_token": obj.get("access_token"),
                "client_id": obj.get("client_id"),
                "client_secret": obj.get("client_secret"),
                "exp": obj.get("exp"),
                "instance_url": obj.get("instance_url"),
                "refresh_token": obj.get("refresh_token"),
            }
        )
        return _obj
