# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from suger_sdk_python.models.github_com_sugerio_marketplace_service_pkg_crud_list_base_response_auditing_event import GithubComSugerioMarketplaceServicePkgCrudListBaseResponseAuditingEvent

from suger_sdk_python.api_client import ApiClient, RequestSerialized
from suger_sdk_python.api_response import ApiResponse
from suger_sdk_python.rest import RESTResponseType


class AuditingApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def query_auditing_events(
        self,
        org_id: Annotated[StrictStr, Field(description="Organization ID")],
        page_size: Annotated[Optional[StrictInt], Field(description="Number of items per page (default: 20, max: 1000)")] = None,
        page_number: Annotated[Optional[StrictInt], Field(description="Page number (default: 1)")] = None,
        q: Annotated[Optional[StrictStr], Field(description="LISP-style filter expression (e.g., '(= event_type \\")] = None,
        s: Annotated[Optional[StrictStr], Field(description="Sort fields: 'field:asc,field2:desc' or '-field,field2' format (e.g., 'creation_time:desc,event_type:asc' or '-creation_time,event_type')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GithubComSugerioMarketplaceServicePkgCrudListBaseResponseAuditingEvent:
        """query auditing events

        Query auditing events with advanced filtering, sorting, and pagination using CRUD query language. Supports complex filters, sorting by multiple fields, and pagination.

        :param org_id: Organization ID (required)
        :type org_id: str
        :param page_size: Number of items per page (default: 20, max: 1000)
        :type page_size: int
        :param page_number: Page number (default: 1)
        :type page_number: int
        :param q: LISP-style filter expression (e.g., '(= event_type \\
        :type q: str
        :param s: Sort fields: 'field:asc,field2:desc' or '-field,field2' format (e.g., 'creation_time:desc,event_type:asc' or '-creation_time,event_type')
        :type s: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_auditing_events_serialize(
            org_id=org_id,
            page_size=page_size,
            page_number=page_number,
            q=q,
            s=s,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GithubComSugerioMarketplaceServicePkgCrudListBaseResponseAuditingEvent",
            '400': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def query_auditing_events_with_http_info(
        self,
        org_id: Annotated[StrictStr, Field(description="Organization ID")],
        page_size: Annotated[Optional[StrictInt], Field(description="Number of items per page (default: 20, max: 1000)")] = None,
        page_number: Annotated[Optional[StrictInt], Field(description="Page number (default: 1)")] = None,
        q: Annotated[Optional[StrictStr], Field(description="LISP-style filter expression (e.g., '(= event_type \\")] = None,
        s: Annotated[Optional[StrictStr], Field(description="Sort fields: 'field:asc,field2:desc' or '-field,field2' format (e.g., 'creation_time:desc,event_type:asc' or '-creation_time,event_type')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GithubComSugerioMarketplaceServicePkgCrudListBaseResponseAuditingEvent]:
        """query auditing events

        Query auditing events with advanced filtering, sorting, and pagination using CRUD query language. Supports complex filters, sorting by multiple fields, and pagination.

        :param org_id: Organization ID (required)
        :type org_id: str
        :param page_size: Number of items per page (default: 20, max: 1000)
        :type page_size: int
        :param page_number: Page number (default: 1)
        :type page_number: int
        :param q: LISP-style filter expression (e.g., '(= event_type \\
        :type q: str
        :param s: Sort fields: 'field:asc,field2:desc' or '-field,field2' format (e.g., 'creation_time:desc,event_type:asc' or '-creation_time,event_type')
        :type s: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_auditing_events_serialize(
            org_id=org_id,
            page_size=page_size,
            page_number=page_number,
            q=q,
            s=s,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GithubComSugerioMarketplaceServicePkgCrudListBaseResponseAuditingEvent",
            '400': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def query_auditing_events_without_preload_content(
        self,
        org_id: Annotated[StrictStr, Field(description="Organization ID")],
        page_size: Annotated[Optional[StrictInt], Field(description="Number of items per page (default: 20, max: 1000)")] = None,
        page_number: Annotated[Optional[StrictInt], Field(description="Page number (default: 1)")] = None,
        q: Annotated[Optional[StrictStr], Field(description="LISP-style filter expression (e.g., '(= event_type \\")] = None,
        s: Annotated[Optional[StrictStr], Field(description="Sort fields: 'field:asc,field2:desc' or '-field,field2' format (e.g., 'creation_time:desc,event_type:asc' or '-creation_time,event_type')")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """query auditing events

        Query auditing events with advanced filtering, sorting, and pagination using CRUD query language. Supports complex filters, sorting by multiple fields, and pagination.

        :param org_id: Organization ID (required)
        :type org_id: str
        :param page_size: Number of items per page (default: 20, max: 1000)
        :type page_size: int
        :param page_number: Page number (default: 1)
        :type page_number: int
        :param q: LISP-style filter expression (e.g., '(= event_type \\
        :type q: str
        :param s: Sort fields: 'field:asc,field2:desc' or '-field,field2' format (e.g., 'creation_time:desc,event_type:asc' or '-creation_time,event_type')
        :type s: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_auditing_events_serialize(
            org_id=org_id,
            page_size=page_size,
            page_number=page_number,
            q=q,
            s=s,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GithubComSugerioMarketplaceServicePkgCrudListBaseResponseAuditingEvent",
            '400': "str",
            '500': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _query_auditing_events_serialize(
        self,
        org_id,
        page_size,
        page_number,
        q,
        s,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if org_id is not None:
            _path_params['orgId'] = org_id
        # process the query parameters
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        if page_number is not None:
            
            _query_params.append(('page_number', page_number))
            
        if q is not None:
            
            _query_params.append(('q', q))
            
        if s is not None:
            
            _query_params.append(('s', s))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/org/{orgId}/auditingEvent/query',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


