# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from suger_sdk_python.models.aws_invoice_line_items import AwsInvoiceLineItems
from typing import Optional, Set
from typing_extensions import Self

class AwsInvoice(BaseModel):
    """
    AwsInvoice
    """ # noqa: E501
    account_id: Optional[StrictStr] = Field(default=None, description="AWS Account ID (12 digits)", alias="accountId")
    amount_due: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Outstanding balance", alias="amountDue")
    billing_entity: Optional[StrictStr] = Field(default=None, description="AWS or AWS_MARKETPLACE - single source of truth for invoice type", alias="billingEntity")
    billing_month: Optional[StrictInt] = Field(default=None, description="Month number (1-12)", alias="billingMonth")
    billing_period_end: Optional[StrictStr] = Field(default=None, description="End of billing period", alias="billingPeriodEnd")
    billing_period_start: Optional[StrictStr] = Field(default=None, description="Start of billing period", alias="billingPeriodStart")
    billing_year: Optional[StrictInt] = Field(default=None, description="Year (YYYY)", alias="billingYear")
    charge_type: Optional[StrictStr] = Field(default=None, description="Anniversary (AWS) or Subscription (Marketplace)", alias="chargeType")
    currency_code: Optional[StrictStr] = Field(default=None, description="CurrencyCode holds the value of the \"currency_code\" field.", alias="currencyCode")
    due_date: Optional[StrictStr] = Field(default=None, description="Payment due date", alias="dueDate")
    id: Optional[StrictStr] = Field(default=None, description="AWS invoice ID (e.g., '2289273833')")
    invoice_type: Optional[StrictStr] = Field(default=None, description="INVOICE or CREDIT_MEMO", alias="invoiceType")
    issued_date: Optional[StrictStr] = Field(default=None, description="When invoice was issued", alias="issuedDate")
    line_items: Optional[AwsInvoiceLineItems] = Field(default=None, description="Extracted line items from PDF processing", alias="lineItems")
    pdf_downloaded: Optional[StrictBool] = Field(default=None, description="PDF download status", alias="pdfDownloaded")
    settle_date: Optional[StrictStr] = Field(default=None, description="Invoice settle date", alias="settleDate")
    status: Optional[StrictStr] = Field(default=None, description="Due, PastDue, Scheduled, Processing, Paid")
    sync_timestamp: Optional[StrictStr] = Field(default=None, description="SyncTimestamp holds the value of the \"sync_timestamp\" field.", alias="syncTimestamp")
    system_identifier_arn: Optional[StrictStr] = Field(default=None, description="ARN from console API (e.g., arn:aws:payments:us-east-1:account:invoice:id)", alias="systemIdentifierArn")
    tax_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Tax amount", alias="taxAmount")
    total_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total invoice amount", alias="totalAmount")
    total_amount_before_tax: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Subtotal before tax", alias="totalAmountBeforeTax")
    transaction_status: Optional[StrictStr] = Field(default=None, description="Forgive, Successful, or Unknown", alias="transactionStatus")
    __properties: ClassVar[List[str]] = ["accountId", "amountDue", "billingEntity", "billingMonth", "billingPeriodEnd", "billingPeriodStart", "billingYear", "chargeType", "currencyCode", "dueDate", "id", "invoiceType", "issuedDate", "lineItems", "pdfDownloaded", "settleDate", "status", "syncTimestamp", "systemIdentifierArn", "taxAmount", "totalAmount", "totalAmountBeforeTax", "transactionStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AwsInvoice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of line_items
        if self.line_items:
            _dict['lineItems'] = self.line_items.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AwsInvoice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountId": obj.get("accountId"),
            "amountDue": obj.get("amountDue"),
            "billingEntity": obj.get("billingEntity"),
            "billingMonth": obj.get("billingMonth"),
            "billingPeriodEnd": obj.get("billingPeriodEnd"),
            "billingPeriodStart": obj.get("billingPeriodStart"),
            "billingYear": obj.get("billingYear"),
            "chargeType": obj.get("chargeType"),
            "currencyCode": obj.get("currencyCode"),
            "dueDate": obj.get("dueDate"),
            "id": obj.get("id"),
            "invoiceType": obj.get("invoiceType"),
            "issuedDate": obj.get("issuedDate"),
            "lineItems": AwsInvoiceLineItems.from_dict(obj["lineItems"]) if obj.get("lineItems") is not None else None,
            "pdfDownloaded": obj.get("pdfDownloaded"),
            "settleDate": obj.get("settleDate"),
            "status": obj.get("status"),
            "syncTimestamp": obj.get("syncTimestamp"),
            "systemIdentifierArn": obj.get("systemIdentifierArn"),
            "taxAmount": obj.get("taxAmount"),
            "totalAmount": obj.get("totalAmount"),
            "totalAmountBeforeTax": obj.get("totalAmountBeforeTax"),
            "transactionStatus": obj.get("transactionStatus")
        })
        return _obj


