# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GcpMarketplacceEventType(str, Enum):
    """
    GcpMarketplacceEventType
    """

    """
    allowed enum values
    """
    GcpMarketplacceEventType_ACCOUNT_ACTIVE = 'ACCOUNT_ACTIVE'
    GcpMarketplacceEventType_ACCOUNT_DELETED = 'ACCOUNT_DELETED'
    GcpMarketplacceEventType_ENTITLEMENT_CREATION_REQUESTED = 'ENTITLEMENT_CREATION_REQUESTED'
    GcpMarketplacceEventType_ENTITLEMENT_ACTIVE = 'ENTITLEMENT_ACTIVE'
    GcpMarketplacceEventType_ENTITLEMENT_PLAN_CHANGE_REQUESTED = 'ENTITLEMENT_PLAN_CHANGE_REQUESTED'
    GcpMarketplacceEventType_ENTITLEMENT_PLAN_CHANGED = 'ENTITLEMENT_PLAN_CHANGED'
    GcpMarketplacceEventType_ENTITLEMENT_PLAN_CHANGE_CANCELLED = 'ENTITLEMENT_PLAN_CHANGE_CANCELLED'
    GcpMarketplacceEventType_ENTITLEMENT_PENDING_CANCELLATION = 'ENTITLEMENT_PENDING_CANCELLATION'
    GcpMarketplacceEventType_ENTITLEMENT_CANCELLATION_REVERTED = 'ENTITLEMENT_CANCELLATION_REVERTED'
    GcpMarketplacceEventType_ENTITLEMENT_CANCELLED = 'ENTITLEMENT_CANCELLED'
    GcpMarketplacceEventType_ENTITLEMENT_CANCELLING = 'ENTITLEMENT_CANCELLING'
    GcpMarketplacceEventType_ENTITLEMENT_RENEWED = 'ENTITLEMENT_RENEWED'
    GcpMarketplacceEventType_ENTITLEMENT_OFFER_ENDED = 'ENTITLEMENT_OFFER_ENDED'
    GcpMarketplacceEventType_ENTITLEMENT_OFFER_ACCEPTED = 'ENTITLEMENT_OFFER_ACCEPTED'
    GcpMarketplacceEventType_ENTITLEMENT_DELETED = 'ENTITLEMENT_DELETED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GcpMarketplacceEventType from a JSON string"""
        return cls(json.loads(json_str))


