# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GcpMarketplaceProductAccessState(str, Enum):
    """
    GcpMarketplaceProductAccessState
    """

    """
    allowed enum values
    """
    GcpMarketplaceProductAccessState_ALLUSERS_ACCESSIBLE = 'ALLUSERS_ACCESSIBLE'
    GcpMarketplaceProductAccessState_NOT_ALLUSERS_ACCESSIBLE = 'NOT_ALLUSERS_ACCESSIBLE'
    GcpMarketplaceProductAccessState_NOT_PUBLISHED = 'NOT_PUBLISHED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GcpMarketplaceProductAccessState from a JSON string"""
        return cls(json.loads(json_str))


