# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from suger_sdk_python.models.operation_filter import OperationFilter
from typing import Optional, Set
from typing_extensions import Self

class ListOperationsV2Request(BaseModel):
    """
    ListOperationsV2Request
    """ # noqa: E501
    filter: Optional[OperationFilter] = Field(default=None, description="Filter expression for querying workflows. Supports nested logical operators (and/or) and comparison operators (=, !=, in, not_in). Example: {\"operator\": \"and\", \"args\": [{\"operator\": \"=\", \"field\": \"SugerService\", \"value\": \"Marketplace\"}, {\"operator\": \"=\", \"field\": \"SugerPartner\", \"value\": \"AWS\"}]}")
    limit: Optional[StrictInt] = Field(default=None, description="Limit the number of results returned (1-100), default 100")
    offset_token: Optional[StrictStr] = Field(default=None, description="OffsetToken for pagination, use nextOffsetToken from previous response", alias="offsetToken")
    __properties: ClassVar[List[str]] = ["filter", "limit", "offsetToken"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListOperationsV2Request from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filter
        if self.filter:
            _dict['filter'] = self.filter.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListOperationsV2Request from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "filter": OperationFilter.from_dict(obj["filter"]) if obj.get("filter") is not None else None,
            "limit": obj.get("limit"),
            "offsetToken": obj.get("offsetToken")
        })
        return _obj


