# coding: utf-8

"""
    Suger API

    CRUD operations on a set of resources, including organizations, products, offers, entitlements, usage record groups for meterting, etc.

    The version of the OpenAPI document: 1.0
    Contact: support@suger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ServiceMarketplaceServiceApiAIUsageRecord(BaseModel):
    """
    ServiceMarketplaceServiceApiAIUsageRecord
    """ # noqa: E501
    cost_microcents: Optional[StrictInt] = Field(default=None, description="CostMicrocents is the total cost in microcents.", alias="costMicrocents")
    cost_usd: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="CostUSD is the total cost in USD.", alias="costUsd")
    hour_bucket: Optional[StrictStr] = Field(default=None, description="HourBucket is the hour this record represents.", alias="hourBucket")
    input_tokens: Optional[StrictInt] = Field(default=None, description="InputTokens is the total input tokens for this hour.", alias="inputTokens")
    is_byok: Optional[StrictBool] = Field(default=None, description="IsBYOK indicates if the organization's own API key was used.", alias="isByok")
    model: Optional[StrictStr] = Field(default=None, description="Model is the model name.")
    output_tokens: Optional[StrictInt] = Field(default=None, description="OutputTokens is the total output tokens for this hour.", alias="outputTokens")
    provider: Optional[StrictStr] = Field(default=None, description="Provider is the AI provider (openai, anthropic, gemini).")
    request_count: Optional[StrictInt] = Field(default=None, description="RequestCount is the number of requests in this hour.", alias="requestCount")
    user_id: Optional[StrictStr] = Field(default=None, description="UserID is the user who made the requests (empty if unattributed).", alias="userId")
    __properties: ClassVar[List[str]] = ["costMicrocents", "costUsd", "hourBucket", "inputTokens", "isByok", "model", "outputTokens", "provider", "requestCount", "userId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceMarketplaceServiceApiAIUsageRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceMarketplaceServiceApiAIUsageRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "costMicrocents": obj.get("costMicrocents"),
            "costUsd": obj.get("costUsd"),
            "hourBucket": obj.get("hourBucket"),
            "inputTokens": obj.get("inputTokens"),
            "isByok": obj.get("isByok"),
            "model": obj.get("model"),
            "outputTokens": obj.get("outputTokens"),
            "provider": obj.get("provider"),
            "requestCount": obj.get("requestCount"),
            "userId": obj.get("userId")
        })
        return _obj


